export type TicketColorThemeId =
  | 'multi'
  | 'ruby'
  | 'emerald'
  | 'amber'
  | 'cyan'
  | 'purple'
  | 'rose'
  | 'sapphire'
  | 'orange'
  | 'lime'
  | 'gold';

export interface RowColorStyle {
  bg: string;
  border: string;
  text: string;
  numberText: string;
  blankBg: string;
  filigreeColor: string;
  dabbedBg: string;
  dabbedText: string;
  dabbedBorder: string;
  label: string;
}

export interface TicketColorTheme {
  id: TicketColorThemeId;
  name: string;
  badgeLabel: string;
  previewHex: string;
  previewGradient: string;
  borderClass: string;
  cardBg: string;
  topBarGradient: string;
  topBarText: string;
  ticketIdBadge: string;
  priceBadge: string;
  progressBadge: string;
  gridBorder: string;
  gridBg: string;
  rows: [RowColorStyle, RowColorStyle, RowColorStyle];
  cellBlankBg: string;
  cellNormalBg: string;
  cellNormalText: string;
  cellNormalBorder: string;
  cellNormalHover: string;
  cellDabbedBg: string;
  cellDabbedText: string;
  cellDabbedBorder: string;
  cellCurrentBg: string;
  checkBadge: string;
  claimPillActive: string;
  printBorder: string;
  printBg: string;
  printCellText: string;
  printWatermark: string;
}

export const COLUMN_COLORS = [
  { header: 'bg-rose-500/30 text-rose-300 border-rose-500/40', cellBg: 'bg-rose-950/40 text-rose-100 border-rose-800/60', dabbed: 'bg-gradient-to-br from-rose-500 via-red-600 to-rose-700 text-white border-rose-300' },
  { header: 'bg-orange-500/30 text-orange-300 border-orange-500/40', cellBg: 'bg-orange-950/40 text-orange-100 border-orange-800/60', dabbed: 'bg-gradient-to-br from-orange-500 via-amber-600 to-orange-700 text-white border-orange-300' },
  { header: 'bg-amber-500/30 text-amber-300 border-amber-500/40', cellBg: 'bg-amber-950/40 text-amber-100 border-amber-800/60', dabbed: 'bg-gradient-to-br from-amber-400 via-yellow-500 to-amber-600 text-slate-950 border-amber-200' },
  { header: 'bg-lime-500/30 text-lime-300 border-lime-500/40', cellBg: 'bg-lime-950/40 text-lime-100 border-lime-800/60', dabbed: 'bg-gradient-to-br from-lime-500 via-emerald-500 to-lime-600 text-slate-950 border-lime-200' },
  { header: 'bg-emerald-500/30 text-emerald-300 border-emerald-500/40', cellBg: 'bg-emerald-950/40 text-emerald-100 border-emerald-800/60', dabbed: 'bg-gradient-to-br from-emerald-500 via-teal-600 to-emerald-700 text-white border-emerald-300' },
  { header: 'bg-cyan-500/30 text-cyan-300 border-cyan-500/40', cellBg: 'bg-cyan-950/40 text-cyan-100 border-cyan-800/60', dabbed: 'bg-gradient-to-br from-cyan-500 via-sky-600 to-blue-600 text-white border-cyan-300' },
  { header: 'bg-blue-500/30 text-blue-300 border-blue-500/40', cellBg: 'bg-blue-950/40 text-blue-100 border-blue-800/60', dabbed: 'bg-gradient-to-br from-blue-500 via-indigo-600 to-blue-700 text-white border-blue-300' },
  { header: 'bg-purple-500/30 text-purple-300 border-purple-500/40', cellBg: 'bg-purple-950/40 text-purple-100 border-purple-800/60', dabbed: 'bg-gradient-to-br from-purple-500 via-fuchsia-600 to-purple-700 text-white border-purple-300' },
  { header: 'bg-pink-500/30 text-pink-300 border-pink-500/40', cellBg: 'bg-pink-950/40 text-pink-100 border-pink-800/60', dabbed: 'bg-gradient-to-br from-pink-500 via-rose-600 to-pink-700 text-white border-pink-300' },
];

export const TICKET_COLOR_PALETTES: Record<Exclude<TicketColorThemeId, 'multi'>, TicketColorTheme> = {
  gold: {
    id: 'gold',
    name: 'Imperial Gold VIP',
    badgeLabel: 'Royal Gold VIP',
    previewHex: '#eab308',
    previewGradient: 'from-amber-400 via-yellow-300 to-amber-500',
    borderClass: 'border-yellow-400/60 hover:border-yellow-300 shadow-amber-500/30',
    cardBg: 'bg-gradient-to-b from-[#1b1406] via-[#100d04] to-[#080602]',
    topBarGradient: 'bg-gradient-to-r from-amber-400 via-yellow-200 to-amber-500',
    topBarText: 'text-slate-950 font-black',
    ticketIdBadge: 'bg-black text-amber-300 border border-amber-400/40',
    priceBadge: 'bg-yellow-300 text-slate-950 font-black',
    progressBadge: 'bg-amber-400/20 text-amber-200 border-amber-400/40',
    gridBorder: 'border-yellow-400/60',
    gridBg: 'bg-gradient-to-b from-[#181105] to-[#0a0702]',
    rows: [
      {
        bg: 'bg-gradient-to-r from-[#fef8e7] via-[#fdf0cd] to-[#fef8e7]',
        border: 'border-amber-300/80',
        text: 'text-amber-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fffcf4]/80 border-amber-200/50',
        filigreeColor: 'text-amber-600/30',
        dabbedBg: 'bg-gradient-to-br from-amber-400 via-yellow-400 to-amber-600 text-slate-950',
        dabbedText: 'text-slate-950 font-black',
        dabbedBorder: 'border-amber-200 ring-2 ring-yellow-200',
        label: 'Row 1 (Gold Top)',
      },
      {
        bg: 'bg-gradient-to-r from-[#fff3e6] via-[#ffe3c7] to-[#fff3e6]',
        border: 'border-orange-300/80',
        text: 'text-orange-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fff8f0]/80 border-orange-200/50',
        filigreeColor: 'text-orange-600/30',
        dabbedBg: 'bg-gradient-to-br from-orange-400 via-amber-500 to-orange-600 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-orange-200 ring-2 ring-yellow-300',
        label: 'Row 2 (Peach Mid)',
      },
      {
        bg: 'bg-gradient-to-r from-[#fefce8] via-[#fef08a]/60 to-[#fefce8]',
        border: 'border-yellow-300/80',
        text: 'text-yellow-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fffeee]/80 border-yellow-200/50',
        filigreeColor: 'text-yellow-600/30',
        dabbedBg: 'bg-gradient-to-br from-yellow-400 via-amber-400 to-yellow-600 text-slate-950',
        dabbedText: 'text-slate-950 font-black',
        dabbedBorder: 'border-yellow-200 ring-2 ring-white',
        label: 'Row 3 (Honey Bot)',
      },
    ],
    cellBlankBg: 'bg-amber-950/30 border-amber-900/40',
    cellNormalBg: 'bg-slate-900/90',
    cellNormalText: 'text-amber-100',
    cellNormalBorder: 'border-amber-800/60',
    cellNormalHover: 'hover:border-amber-300 hover:bg-amber-950/50',
    cellDabbedBg: 'bg-gradient-to-br from-yellow-400 via-amber-500 to-yellow-600',
    cellDabbedText: 'text-slate-950 font-black',
    cellDabbedBorder: 'border-yellow-200 shadow-lg shadow-amber-500/40',
    cellCurrentBg: 'bg-gradient-to-br from-white to-amber-100 text-slate-950 ring-2 ring-yellow-200',
    checkBadge: 'bg-slate-950 text-amber-300',
    claimPillActive: 'bg-gradient-to-r from-yellow-300 via-amber-400 to-yellow-500 text-slate-950 font-black',
    printBorder: 'border-yellow-400',
    printBg: 'from-[#2e230a] via-[#1a1304] to-[#2e230a]',
    printCellText: 'text-amber-200',
    printWatermark: 'text-yellow-400',
  },

  ruby: {
    id: 'ruby',
    name: 'Ruby Crimson',
    badgeLabel: 'Ruby Red',
    previewHex: '#ef4444',
    previewGradient: 'from-red-600 via-rose-500 to-red-700',
    borderClass: 'border-red-500/50 hover:border-red-400 shadow-red-500/20',
    cardBg: 'bg-gradient-to-b from-[#1a080e] via-[#100508] to-[#080204]',
    topBarGradient: 'bg-gradient-to-r from-red-600 via-rose-500 to-red-700',
    topBarText: 'text-white',
    ticketIdBadge: 'bg-black/70 text-rose-300 border border-rose-500/30',
    priceBadge: 'bg-red-400 text-slate-950 font-black',
    progressBadge: 'bg-rose-500/20 text-rose-300 border-rose-500/40',
    gridBorder: 'border-red-500/50',
    gridBg: 'bg-gradient-to-b from-[#16060c] to-[#0a0205]',
    rows: [
      {
        bg: 'bg-gradient-to-r from-[#ffebee] via-[#ffcdd2] to-[#ffebee]',
        border: 'border-red-300/80',
        text: 'text-red-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fff5f6]/80 border-red-200/50',
        filigreeColor: 'text-red-600/30',
        dabbedBg: 'bg-gradient-to-br from-red-600 via-rose-600 to-red-700 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-rose-300 ring-2 ring-yellow-300',
        label: 'Row 1 (Rose Top)',
      },
      {
        bg: 'bg-gradient-to-r from-[#fce4ec] via-[#f8bbd0] to-[#fce4ec]',
        border: 'border-pink-300/80',
        text: 'text-pink-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fff0f5]/80 border-pink-200/50',
        filigreeColor: 'text-pink-600/30',
        dabbedBg: 'bg-gradient-to-br from-pink-600 via-rose-500 to-fuchsia-700 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-pink-300 ring-2 ring-yellow-300',
        label: 'Row 2 (Crimson Mid)',
      },
      {
        bg: 'bg-gradient-to-r from-[#fff3e0] via-[#ffe0b2] to-[#fff3e0]',
        border: 'border-orange-300/80',
        text: 'text-orange-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fff8ee]/80 border-orange-200/50',
        filigreeColor: 'text-orange-600/30',
        dabbedBg: 'bg-gradient-to-br from-orange-500 via-red-600 to-orange-700 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-orange-300 ring-2 ring-yellow-300',
        label: 'Row 3 (Coral Bot)',
      },
    ],
    cellBlankBg: 'bg-red-950/20 border-red-950/40',
    cellNormalBg: 'bg-slate-900/90',
    cellNormalText: 'text-rose-100',
    cellNormalBorder: 'border-red-900/60',
    cellNormalHover: 'hover:border-red-400 hover:bg-red-950/40',
    cellDabbedBg: 'bg-gradient-to-br from-red-600 via-rose-600 to-red-800',
    cellDabbedText: 'text-white',
    cellDabbedBorder: 'border-red-400/70 shadow-md shadow-red-900/50',
    cellCurrentBg: 'bg-gradient-to-br from-amber-400 to-amber-500 text-slate-950 ring-2 ring-amber-300',
    checkBadge: 'bg-amber-400 text-slate-950',
    claimPillActive: 'bg-gradient-to-r from-red-500 to-rose-600 text-white',
    printBorder: 'border-red-500',
    printBg: 'from-[#200d14] via-[#14090f] to-[#200d14]',
    printCellText: 'text-rose-300',
    printWatermark: 'text-rose-500',
  },

  emerald: {
    id: 'emerald',
    name: 'Emerald Forest',
    badgeLabel: 'Emerald Jade',
    previewHex: '#10b981',
    previewGradient: 'from-emerald-600 via-teal-500 to-emerald-700',
    borderClass: 'border-emerald-500/50 hover:border-emerald-400 shadow-emerald-500/20',
    cardBg: 'bg-gradient-to-b from-[#081812] via-[#05100c] to-[#020806]',
    topBarGradient: 'bg-gradient-to-r from-emerald-600 via-teal-500 to-emerald-700',
    topBarText: 'text-slate-950 font-black',
    ticketIdBadge: 'bg-slate-950/80 text-emerald-300 border border-emerald-500/30',
    priceBadge: 'bg-emerald-300 text-slate-950 font-black',
    progressBadge: 'bg-emerald-500/20 text-emerald-300 border-emerald-500/40',
    gridBorder: 'border-emerald-500/50',
    gridBg: 'bg-gradient-to-b from-[#06140f] to-[#020a07]',
    rows: [
      {
        bg: 'bg-gradient-to-r from-[#e8f5e9] via-[#c8e6c9] to-[#e8f5e9]',
        border: 'border-emerald-300/80',
        text: 'text-emerald-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#f3faf4]/80 border-emerald-200/50',
        filigreeColor: 'text-emerald-600/30',
        dabbedBg: 'bg-gradient-to-br from-emerald-600 via-teal-600 to-emerald-700 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-emerald-300 ring-2 ring-yellow-300',
        label: 'Row 1 (Mint Top)',
      },
      {
        bg: 'bg-gradient-to-r from-[#e0f2f1] via-[#b2dfdb] to-[#e0f2f1]',
        border: 'border-teal-300/80',
        text: 'text-teal-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#f0f9f8]/80 border-teal-200/50',
        filigreeColor: 'text-teal-600/30',
        dabbedBg: 'bg-gradient-to-br from-teal-600 via-emerald-600 to-teal-800 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-teal-300 ring-2 ring-yellow-300',
        label: 'Row 2 (Sage Mid)',
      },
      {
        bg: 'bg-gradient-to-r from-[#f1f8e9] via-[#dcedc8] to-[#f1f8e9]',
        border: 'border-lime-300/80',
        text: 'text-lime-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#f8fcf3]/80 border-lime-200/50',
        filigreeColor: 'text-lime-600/30',
        dabbedBg: 'bg-gradient-to-br from-lime-500 via-emerald-500 to-lime-700 text-slate-950',
        dabbedText: 'text-slate-950 font-black',
        dabbedBorder: 'border-lime-300 ring-2 ring-white',
        label: 'Row 3 (Lime Bot)',
      },
    ],
    cellBlankBg: 'bg-emerald-950/20 border-emerald-950/40',
    cellNormalBg: 'bg-slate-900/90',
    cellNormalText: 'text-emerald-100',
    cellNormalBorder: 'border-emerald-900/60',
    cellNormalHover: 'hover:border-emerald-400 hover:bg-emerald-950/40',
    cellDabbedBg: 'bg-gradient-to-br from-emerald-600 via-teal-600 to-emerald-800',
    cellDabbedText: 'text-white',
    cellDabbedBorder: 'border-emerald-400/70 shadow-md shadow-emerald-900/50',
    cellCurrentBg: 'bg-gradient-to-br from-amber-400 to-amber-500 text-slate-950 ring-2 ring-amber-300',
    checkBadge: 'bg-amber-400 text-slate-950',
    claimPillActive: 'bg-gradient-to-r from-emerald-500 to-teal-600 text-white',
    printBorder: 'border-emerald-500',
    printBg: 'from-[#0d221b] via-[#071712] to-[#0d221b]',
    printCellText: 'text-emerald-300',
    printWatermark: 'text-emerald-500',
  },

  cyan: {
    id: 'cyan',
    name: 'Electric Cyan',
    badgeLabel: 'Neon Cyan',
    previewHex: '#06b6d4',
    previewGradient: 'from-cyan-500 via-sky-500 to-blue-600',
    borderClass: 'border-cyan-500/50 hover:border-cyan-400 shadow-cyan-500/20',
    cardBg: 'bg-gradient-to-b from-[#081522] via-[#050e18] to-[#02070c]',
    topBarGradient: 'bg-gradient-to-r from-cyan-500 via-sky-400 to-blue-600',
    topBarText: 'text-slate-950 font-black',
    ticketIdBadge: 'bg-slate-950/80 text-cyan-300 border border-cyan-500/30',
    priceBadge: 'bg-cyan-300 text-slate-950 font-black',
    progressBadge: 'bg-cyan-500/20 text-cyan-300 border-cyan-500/40',
    gridBorder: 'border-cyan-500/50',
    gridBg: 'bg-gradient-to-b from-[#05111c] to-[#02080e]',
    rows: [
      {
        bg: 'bg-gradient-to-r from-[#e0f7fa] via-[#b2ebf2] to-[#e0f7fa]',
        border: 'border-cyan-300/80',
        text: 'text-cyan-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#f0fbfe]/80 border-cyan-200/50',
        filigreeColor: 'text-cyan-600/30',
        dabbedBg: 'bg-gradient-to-br from-cyan-500 via-sky-500 to-blue-600 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-cyan-300 ring-2 ring-yellow-300',
        label: 'Row 1 (Aqua Top)',
      },
      {
        bg: 'bg-gradient-to-r from-[#e1f5fe] via-[#b3e5fc] to-[#e1f5fe]',
        border: 'border-sky-300/80',
        text: 'text-sky-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#f1faff]/80 border-sky-200/50',
        filigreeColor: 'text-sky-600/30',
        dabbedBg: 'bg-gradient-to-br from-sky-500 via-blue-600 to-indigo-700 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-sky-300 ring-2 ring-yellow-300',
        label: 'Row 2 (Sky Mid)',
      },
      {
        bg: 'bg-gradient-to-r from-[#e8eaf6] via-[#c5cae9] to-[#e8eaf6]',
        border: 'border-indigo-300/80',
        text: 'text-indigo-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#f4f5fc]/80 border-indigo-200/50',
        filigreeColor: 'text-indigo-600/30',
        dabbedBg: 'bg-gradient-to-br from-indigo-500 via-purple-600 to-blue-700 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-indigo-300 ring-2 ring-yellow-300',
        label: 'Row 3 (Periwinkle Bot)',
      },
    ],
    cellBlankBg: 'bg-cyan-950/20 border-cyan-950/40',
    cellNormalBg: 'bg-slate-900/90',
    cellNormalText: 'text-cyan-100',
    cellNormalBorder: 'border-cyan-900/60',
    cellNormalHover: 'hover:border-cyan-400 hover:bg-cyan-950/40',
    cellDabbedBg: 'bg-gradient-to-br from-cyan-600 via-sky-600 to-blue-700',
    cellDabbedText: 'text-white',
    cellDabbedBorder: 'border-cyan-400/70 shadow-md shadow-cyan-900/50',
    cellCurrentBg: 'bg-gradient-to-br from-amber-400 to-amber-500 text-slate-950 ring-2 ring-amber-300',
    checkBadge: 'bg-amber-400 text-slate-950',
    claimPillActive: 'bg-gradient-to-r from-cyan-500 to-blue-600 text-white',
    printBorder: 'border-cyan-500',
    printBg: 'from-[#0c1f33] via-[#081524] to-[#0c1f33]',
    printCellText: 'text-cyan-300',
    printWatermark: 'text-cyan-500',
  },

  purple: {
    id: 'purple',
    name: 'Velvet Purple',
    badgeLabel: 'Royal Amethyst',
    previewHex: '#a855f7',
    previewGradient: 'from-purple-600 via-indigo-500 to-purple-800',
    borderClass: 'border-purple-500/50 hover:border-purple-400 shadow-purple-500/20',
    cardBg: 'bg-gradient-to-b from-[#140c24] via-[#0c0717] to-[#06030c]',
    topBarGradient: 'bg-gradient-to-r from-purple-600 via-fuchsia-500 to-indigo-700',
    topBarText: 'text-white',
    ticketIdBadge: 'bg-slate-950/80 text-purple-300 border border-purple-500/30',
    priceBadge: 'bg-purple-300 text-slate-950 font-black',
    progressBadge: 'bg-purple-500/20 text-purple-300 border-purple-500/40',
    gridBorder: 'border-purple-500/50',
    gridBg: 'bg-gradient-to-b from-[#10081e] to-[#06030c]',
    rows: [
      {
        bg: 'bg-gradient-to-r from-[#f3e5f5] via-[#e1bee7] to-[#f3e5f5]',
        border: 'border-purple-300/80',
        text: 'text-purple-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#faf3fb]/80 border-purple-200/50',
        filigreeColor: 'text-purple-600/30',
        dabbedBg: 'bg-gradient-to-br from-purple-600 via-fuchsia-600 to-purple-800 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-purple-300 ring-2 ring-yellow-300',
        label: 'Row 1 (Lilac Top)',
      },
      {
        bg: 'bg-gradient-to-r from-[#ede7f6] via-[#d1c4e9] to-[#ede7f6]',
        border: 'border-indigo-300/80',
        text: 'text-indigo-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#f6f3fb]/80 border-indigo-200/50',
        filigreeColor: 'text-indigo-600/30',
        dabbedBg: 'bg-gradient-to-br from-indigo-600 via-purple-600 to-indigo-800 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-indigo-300 ring-2 ring-yellow-300',
        label: 'Row 2 (Violet Mid)',
      },
      {
        bg: 'bg-gradient-to-r from-[#fce4ec] via-[#f8bbd0] to-[#fce4ec]',
        border: 'border-pink-300/80',
        text: 'text-pink-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fff1f6]/80 border-pink-200/50',
        filigreeColor: 'text-pink-600/30',
        dabbedBg: 'bg-gradient-to-br from-pink-600 via-purple-600 to-rose-700 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-pink-300 ring-2 ring-yellow-300',
        label: 'Row 3 (Orchid Bot)',
      },
    ],
    cellBlankBg: 'bg-purple-950/20 border-purple-950/40',
    cellNormalBg: 'bg-slate-900/90',
    cellNormalText: 'text-purple-100',
    cellNormalBorder: 'border-purple-900/60',
    cellNormalHover: 'hover:border-purple-400 hover:bg-purple-950/40',
    cellDabbedBg: 'bg-gradient-to-br from-purple-600 via-indigo-600 to-purple-800',
    cellDabbedText: 'text-white',
    cellDabbedBorder: 'border-purple-400/70 shadow-md shadow-purple-900/50',
    cellCurrentBg: 'bg-gradient-to-br from-amber-400 to-amber-500 text-slate-950 ring-2 ring-amber-300',
    checkBadge: 'bg-amber-400 text-slate-950',
    claimPillActive: 'bg-gradient-to-r from-purple-500 to-fuchsia-600 text-white',
    printBorder: 'border-purple-500',
    printBg: 'from-[#1f1338] via-[#130b24] to-[#1f1338]',
    printCellText: 'text-purple-300',
    printWatermark: 'text-purple-500',
  },

  amber: {
    id: 'amber',
    name: 'Golden Amber',
    badgeLabel: 'Sunset Gold',
    previewHex: '#f59e0b',
    previewGradient: 'from-amber-500 via-yellow-500 to-amber-600',
    borderClass: 'border-amber-500/50 hover:border-amber-400 shadow-amber-500/20',
    cardBg: 'bg-gradient-to-b from-[#1c1207] via-[#120a04] to-[#080402]',
    topBarGradient: 'bg-gradient-to-r from-amber-500 via-yellow-400 to-amber-600',
    topBarText: 'text-slate-950 font-black',
    ticketIdBadge: 'bg-slate-950/80 text-amber-300 border border-amber-500/30',
    priceBadge: 'bg-amber-400 text-slate-950 font-black',
    progressBadge: 'bg-amber-500/20 text-amber-300 border-amber-500/40',
    gridBorder: 'border-amber-500/50',
    gridBg: 'bg-gradient-to-b from-[#140c05] to-[#070402]',
    rows: [
      {
        bg: 'bg-gradient-to-r from-[#fef3c7] via-[#fde68a] to-[#fef3c7]',
        border: 'border-amber-300/80',
        text: 'text-amber-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fffbeb]/80 border-amber-200/50',
        filigreeColor: 'text-amber-600/30',
        dabbedBg: 'bg-gradient-to-br from-amber-500 via-orange-500 to-amber-600 text-slate-950',
        dabbedText: 'text-slate-950 font-black',
        dabbedBorder: 'border-amber-200 ring-2 ring-white',
        label: 'Row 1 (Sunrise Top)',
      },
      {
        bg: 'bg-gradient-to-r from-[#ffedd5] via-[#fed7aa] to-[#ffedd5]',
        border: 'border-orange-300/80',
        text: 'text-orange-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fff7ed]/80 border-orange-200/50',
        filigreeColor: 'text-orange-600/30',
        dabbedBg: 'bg-gradient-to-br from-orange-500 via-amber-500 to-red-600 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-orange-200 ring-2 ring-yellow-300',
        label: 'Row 2 (Marigold Mid)',
      },
      {
        bg: 'bg-gradient-to-r from-[#fef9c3] via-[#fef08a] to-[#fef9c3]',
        border: 'border-yellow-300/80',
        text: 'text-yellow-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fefce8]/80 border-yellow-200/50',
        filigreeColor: 'text-yellow-600/30',
        dabbedBg: 'bg-gradient-to-br from-yellow-400 via-amber-400 to-yellow-600 text-slate-950',
        dabbedText: 'text-slate-950 font-black',
        dabbedBorder: 'border-yellow-200 ring-2 ring-slate-900',
        label: 'Row 3 (Butter Bot)',
      },
    ],
    cellBlankBg: 'bg-amber-950/20 border-amber-950/40',
    cellNormalBg: 'bg-slate-900/90',
    cellNormalText: 'text-amber-100',
    cellNormalBorder: 'border-amber-900/60',
    cellNormalHover: 'hover:border-amber-400 hover:bg-amber-950/40',
    cellDabbedBg: 'bg-gradient-to-br from-amber-500 via-orange-500 to-amber-700',
    cellDabbedText: 'text-slate-950 font-black',
    cellDabbedBorder: 'border-amber-300 shadow-md shadow-amber-900/50',
    cellCurrentBg: 'bg-gradient-to-br from-white to-amber-200 text-slate-950 ring-2 ring-white',
    checkBadge: 'bg-slate-950 text-amber-400',
    claimPillActive: 'bg-gradient-to-r from-amber-400 to-yellow-500 text-slate-950 font-bold',
    printBorder: 'border-amber-500',
    printBg: 'from-[#2a1b0a] via-[#170e05] to-[#2a1b0a]',
    printCellText: 'text-amber-300',
    printWatermark: 'text-amber-500',
  },

  rose: {
    id: 'rose',
    name: 'Rose Blossom',
    badgeLabel: 'Neon Blossom',
    previewHex: '#f43f5e',
    previewGradient: 'from-pink-500 via-rose-500 to-pink-700',
    borderClass: 'border-pink-500/50 hover:border-pink-400 shadow-pink-500/20',
    cardBg: 'bg-gradient-to-b from-[#1d0914] via-[#11050b] to-[#070204]',
    topBarGradient: 'bg-gradient-to-r from-pink-500 via-rose-400 to-pink-700',
    topBarText: 'text-white',
    ticketIdBadge: 'bg-slate-950/80 text-pink-300 border border-pink-500/30',
    priceBadge: 'bg-pink-300 text-slate-950 font-black',
    progressBadge: 'bg-pink-500/20 text-pink-300 border-pink-500/40',
    gridBorder: 'border-pink-500/50',
    gridBg: 'bg-gradient-to-b from-[#14060e] to-[#070204]',
    rows: [
      {
        bg: 'bg-gradient-to-r from-[#ffe4e6] via-[#fecdd3] to-[#ffe4e6]',
        border: 'border-rose-300/80',
        text: 'text-rose-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fff1f2]/80 border-rose-200/50',
        filigreeColor: 'text-rose-600/30',
        dabbedBg: 'bg-gradient-to-br from-rose-500 via-pink-600 to-rose-700 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-rose-300 ring-2 ring-yellow-300',
        label: 'Row 1 (Rose Top)',
      },
      {
        bg: 'bg-gradient-to-r from-[#fdf2f8] via-[#fce7f3] to-[#fdf2f8]',
        border: 'border-pink-300/80',
        text: 'text-pink-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fdf4f9]/80 border-pink-200/50',
        filigreeColor: 'text-pink-600/30',
        dabbedBg: 'bg-gradient-to-br from-pink-500 via-fuchsia-600 to-rose-600 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-pink-300 ring-2 ring-yellow-300',
        label: 'Row 2 (Blossom Mid)',
      },
      {
        bg: 'bg-gradient-to-r from-[#fae8ff] via-[#f5d0fe] to-[#fae8ff]',
        border: 'border-fuchsia-300/80',
        text: 'text-fuchsia-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#faf0fc]/80 border-fuchsia-200/50',
        filigreeColor: 'text-fuchsia-600/30',
        dabbedBg: 'bg-gradient-to-br from-fuchsia-500 via-pink-600 to-purple-700 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-fuchsia-300 ring-2 ring-yellow-300',
        label: 'Row 3 (Fuchsia Bot)',
      },
    ],
    cellBlankBg: 'bg-pink-950/20 border-pink-950/40',
    cellNormalBg: 'bg-slate-900/90',
    cellNormalText: 'text-pink-100',
    cellNormalBorder: 'border-pink-900/60',
    cellNormalHover: 'hover:border-pink-400 hover:bg-pink-950/40',
    cellDabbedBg: 'bg-gradient-to-br from-pink-600 via-rose-600 to-pink-800',
    cellDabbedText: 'text-white',
    cellDabbedBorder: 'border-pink-400/70 shadow-md shadow-pink-900/50',
    cellCurrentBg: 'bg-gradient-to-br from-amber-400 to-amber-500 text-slate-950 ring-2 ring-amber-300',
    checkBadge: 'bg-amber-400 text-slate-950',
    claimPillActive: 'bg-gradient-to-r from-pink-500 to-rose-600 text-white',
    printBorder: 'border-pink-500',
    printBg: 'from-[#2b0f1e] via-[#180811] to-[#2b0f1e]',
    printCellText: 'text-pink-300',
    printWatermark: 'text-pink-500',
  },

  sapphire: {
    id: 'sapphire',
    name: 'Sapphire Blue',
    badgeLabel: 'Deep Ocean',
    previewHex: '#3b82f6',
    previewGradient: 'from-blue-600 via-indigo-600 to-blue-800',
    borderClass: 'border-blue-500/50 hover:border-blue-400 shadow-blue-500/20',
    cardBg: 'bg-gradient-to-b from-[#091224] via-[#050b16] to-[#02050b]',
    topBarGradient: 'bg-gradient-to-r from-blue-600 via-indigo-500 to-blue-800',
    topBarText: 'text-white',
    ticketIdBadge: 'bg-slate-950/80 text-blue-300 border border-blue-500/30',
    priceBadge: 'bg-blue-300 text-slate-950 font-black',
    progressBadge: 'bg-blue-500/20 text-blue-300 border-blue-500/40',
    gridBorder: 'border-blue-500/50',
    gridBg: 'bg-gradient-to-b from-[#070e1c] to-[#02050b]',
    rows: [
      {
        bg: 'bg-gradient-to-r from-[#e0f2fe] via-[#bae6fd] to-[#e0f2fe]',
        border: 'border-sky-300/80',
        text: 'text-sky-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#f0f9ff]/80 border-sky-200/50',
        filigreeColor: 'text-sky-600/30',
        dabbedBg: 'bg-gradient-to-br from-sky-500 via-blue-600 to-indigo-700 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-sky-300 ring-2 ring-yellow-300',
        label: 'Row 1 (Ice Blue Top)',
      },
      {
        bg: 'bg-gradient-to-r from-[#dbeafe] via-[#bfdbfe] to-[#dbeafe]',
        border: 'border-blue-300/80',
        text: 'text-blue-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#eff6ff]/80 border-blue-200/50',
        filigreeColor: 'text-blue-600/30',
        dabbedBg: 'bg-gradient-to-br from-blue-600 via-indigo-600 to-blue-800 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-blue-300 ring-2 ring-yellow-300',
        label: 'Row 2 (Sapphire Mid)',
      },
      {
        bg: 'bg-gradient-to-r from-[#e0e7ff] via-[#c7d2fe] to-[#e0e7ff]',
        border: 'border-indigo-300/80',
        text: 'text-indigo-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#eef2ff]/80 border-indigo-200/50',
        filigreeColor: 'text-indigo-600/30',
        dabbedBg: 'bg-gradient-to-br from-indigo-600 via-purple-600 to-blue-700 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-indigo-300 ring-2 ring-yellow-300',
        label: 'Row 3 (Cobalt Bot)',
      },
    ],
    cellBlankBg: 'bg-blue-950/20 border-blue-950/40',
    cellNormalBg: 'bg-slate-900/90',
    cellNormalText: 'text-blue-100',
    cellNormalBorder: 'border-blue-900/60',
    cellNormalHover: 'hover:border-blue-400 hover:bg-blue-950/40',
    cellDabbedBg: 'bg-gradient-to-br from-blue-600 via-indigo-600 to-blue-800',
    cellDabbedText: 'text-white',
    cellDabbedBorder: 'border-blue-400/70 shadow-md shadow-blue-900/50',
    cellCurrentBg: 'bg-gradient-to-br from-amber-400 to-amber-500 text-slate-950 ring-2 ring-amber-300',
    checkBadge: 'bg-amber-400 text-slate-950',
    claimPillActive: 'bg-gradient-to-r from-blue-500 to-indigo-600 text-white',
    printBorder: 'border-blue-500',
    printBg: 'from-[#0f1d3d] via-[#091226] to-[#0f1d3d]',
    printCellText: 'text-blue-300',
    printWatermark: 'text-blue-500',
  },

  orange: {
    id: 'orange',
    name: 'Sunset Blaze',
    badgeLabel: 'Flame Orange',
    previewHex: '#f97316',
    previewGradient: 'from-orange-500 via-amber-500 to-red-600',
    borderClass: 'border-orange-500/50 hover:border-orange-400 shadow-orange-500/20',
    cardBg: 'bg-gradient-to-b from-[#1c0e08] via-[#110804] to-[#070302]',
    topBarGradient: 'bg-gradient-to-r from-orange-500 via-amber-500 to-red-600',
    topBarText: 'text-slate-950 font-black',
    ticketIdBadge: 'bg-slate-950/80 text-orange-300 border border-orange-500/30',
    priceBadge: 'bg-orange-300 text-slate-950 font-black',
    progressBadge: 'bg-orange-500/20 text-orange-300 border-orange-500/40',
    gridBorder: 'border-orange-500/50',
    gridBg: 'bg-gradient-to-b from-[#130905] to-[#060301]',
    rows: [
      {
        bg: 'bg-gradient-to-r from-[#ffedd5] via-[#fed7aa] to-[#ffedd5]',
        border: 'border-orange-300/80',
        text: 'text-orange-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fff7ed]/80 border-orange-200/50',
        filigreeColor: 'text-orange-600/30',
        dabbedBg: 'bg-gradient-to-br from-orange-500 via-amber-500 to-red-600 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-orange-300 ring-2 ring-yellow-300',
        label: 'Row 1 (Tangerine Top)',
      },
      {
        bg: 'bg-gradient-to-r from-[#ffe4e6] via-[#fecdd3] to-[#ffe4e6]',
        border: 'border-rose-300/80',
        text: 'text-rose-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fff1f2]/80 border-rose-200/50',
        filigreeColor: 'text-rose-600/30',
        dabbedBg: 'bg-gradient-to-br from-rose-500 via-red-600 to-orange-600 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-rose-300 ring-2 ring-yellow-300',
        label: 'Row 2 (Coral Mid)',
      },
      {
        bg: 'bg-gradient-to-r from-[#fef3c7] via-[#fde68a] to-[#fef3c7]',
        border: 'border-yellow-300/80',
        text: 'text-yellow-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fffbeb]/80 border-yellow-200/50',
        filigreeColor: 'text-yellow-600/30',
        dabbedBg: 'bg-gradient-to-br from-yellow-400 via-orange-500 to-amber-600 text-slate-950',
        dabbedText: 'text-slate-950 font-black',
        dabbedBorder: 'border-yellow-200 ring-2 ring-white',
        label: 'Row 3 (Sunburst Bot)',
      },
    ],
    cellBlankBg: 'bg-orange-950/20 border-orange-950/40',
    cellNormalBg: 'bg-slate-900/90',
    cellNormalText: 'text-orange-100',
    cellNormalBorder: 'border-orange-900/60',
    cellNormalHover: 'hover:border-orange-400 hover:bg-orange-950/40',
    cellDabbedBg: 'bg-gradient-to-br from-orange-500 via-amber-600 to-red-600',
    cellDabbedText: 'text-white',
    cellDabbedBorder: 'border-orange-400/70 shadow-md shadow-orange-900/50',
    cellCurrentBg: 'bg-gradient-to-br from-yellow-300 to-amber-400 text-slate-950 ring-2 ring-yellow-200',
    checkBadge: 'bg-slate-950 text-orange-400',
    claimPillActive: 'bg-gradient-to-r from-orange-500 to-amber-500 text-slate-950 font-bold',
    printBorder: 'border-orange-500',
    printBg: 'from-[#2e180e] via-[#1a0e08] to-[#2e180e]',
    printCellText: 'text-orange-300',
    printWatermark: 'text-orange-500',
  },

  lime: {
    id: 'lime',
    name: 'Neon Lime',
    badgeLabel: 'Electric Lime',
    previewHex: '#84cc16',
    previewGradient: 'from-lime-500 via-emerald-400 to-lime-600',
    borderClass: 'border-lime-500/50 hover:border-lime-400 shadow-lime-500/20',
    cardBg: 'bg-gradient-to-b from-[#0f1706] via-[#090e03] to-[#040601]',
    topBarGradient: 'bg-gradient-to-r from-lime-500 via-emerald-400 to-lime-600',
    topBarText: 'text-slate-950 font-black',
    ticketIdBadge: 'bg-slate-950/80 text-lime-300 border border-lime-500/30',
    priceBadge: 'bg-lime-400 text-slate-950 font-black',
    progressBadge: 'bg-lime-500/20 text-lime-300 border-lime-500/40',
    gridBorder: 'border-lime-500/50',
    gridBg: 'bg-gradient-to-b from-[#0a1004] to-[#040601]',
    rows: [
      {
        bg: 'bg-gradient-to-r from-[#f7fee7] via-[#d9f99d] to-[#f7fee7]',
        border: 'border-lime-300/80',
        text: 'text-lime-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fafef2]/80 border-lime-200/50',
        filigreeColor: 'text-lime-600/30',
        dabbedBg: 'bg-gradient-to-br from-lime-500 via-emerald-500 to-lime-700 text-slate-950',
        dabbedText: 'text-slate-950 font-black',
        dabbedBorder: 'border-lime-300 ring-2 ring-white',
        label: 'Row 1 (Lime Top)',
      },
      {
        bg: 'bg-gradient-to-r from-[#ecfdf5] via-[#a7f3d0] to-[#ecfdf5]',
        border: 'border-emerald-300/80',
        text: 'text-emerald-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#f4fdf8]/80 border-emerald-200/50',
        filigreeColor: 'text-emerald-600/30',
        dabbedBg: 'bg-gradient-to-br from-emerald-500 via-teal-600 to-emerald-700 text-white',
        dabbedText: 'text-white font-black',
        dabbedBorder: 'border-emerald-300 ring-2 ring-yellow-300',
        label: 'Row 2 (Emerald Mid)',
      },
      {
        bg: 'bg-gradient-to-r from-[#fefce8] via-[#fef08a] to-[#fefce8]',
        border: 'border-yellow-300/80',
        text: 'text-yellow-950',
        numberText: 'text-slate-950 font-black font-sans',
        blankBg: 'bg-[#fffdee]/80 border-yellow-200/50',
        filigreeColor: 'text-yellow-600/30',
        dabbedBg: 'bg-gradient-to-br from-yellow-400 via-lime-400 to-amber-500 text-slate-950',
        dabbedText: 'text-slate-950 font-black',
        dabbedBorder: 'border-yellow-200 ring-2 ring-slate-900',
        label: 'Row 3 (Citrus Bot)',
      },
    ],
    cellBlankBg: 'bg-lime-950/20 border-lime-950/40',
    cellNormalBg: 'bg-slate-900/90',
    cellNormalText: 'text-lime-100',
    cellNormalBorder: 'border-lime-900/60',
    cellNormalHover: 'hover:border-lime-400 hover:bg-lime-950/40',
    cellDabbedBg: 'bg-gradient-to-br from-lime-500 via-emerald-500 to-lime-700',
    cellDabbedText: 'text-slate-950 font-black',
    cellDabbedBorder: 'border-lime-300 shadow-md shadow-lime-900/50',
    cellCurrentBg: 'bg-gradient-to-br from-white to-amber-300 text-slate-950 ring-2 ring-white',
    checkBadge: 'bg-slate-950 text-lime-400',
    claimPillActive: 'bg-gradient-to-r from-lime-400 to-emerald-500 text-slate-950 font-bold',
    printBorder: 'border-lime-500',
    printBg: 'from-[#1b270a] via-[#0e1605] to-[#1b270a]',
    printCellText: 'text-lime-300',
    printWatermark: 'text-lime-500',
  },
};

export const COLOR_KEYS: Exclude<TicketColorThemeId, 'multi'>[] = [
  'gold',
  'ruby',
  'emerald',
  'cyan',
  'purple',
  'amber',
  'rose',
  'sapphire',
  'orange',
  'lime',
];

/**
 * Default Ultra-Colorful Multi Carnival Theme (Inspired by official APNA TAMBOLA ticket card)
 */
export const MULTI_CARNIVAL_THEME: TicketColorTheme = {
  id: 'multi',
  name: '★ Apna Tambola Classic Carnival ★',
  badgeLabel: 'Carnival Multi-Color',
  previewHex: '#38bdf8',
  previewGradient: 'from-sky-400 via-pink-400 to-lime-400',
  borderClass: 'border-amber-400/80 hover:border-yellow-300 shadow-amber-500/30',
  cardBg: 'bg-gradient-to-b from-[#180f28] via-[#0d091a] to-[#06040e]',
  topBarGradient: 'bg-gradient-to-r from-amber-400 via-yellow-300 to-amber-500',
  topBarText: 'text-slate-950 font-black',
  ticketIdBadge: 'bg-black text-amber-300 border border-amber-400/40 font-mono',
  priceBadge: 'bg-yellow-300 text-slate-950 font-black',
  progressBadge: 'bg-amber-400/20 text-amber-200 border-amber-400/40',
  gridBorder: 'border-amber-400/70',
  gridBg: 'bg-gradient-to-b from-[#140b22] to-[#07040f]',
  rows: [
    {
      bg: 'bg-gradient-to-b from-[#e3f3fe] via-[#cce7fd] to-[#badffc]',
      border: 'border-sky-300',
      text: 'text-slate-950',
      numberText: 'text-slate-950 font-black font-sans',
      blankBg: 'bg-[#edf7ff]/80 border-sky-200/50',
      filigreeColor: 'text-sky-600/30',
      dabbedBg: 'bg-gradient-to-br from-blue-600 via-sky-500 to-indigo-700 text-white',
      dabbedText: 'text-white font-black',
      dabbedBorder: 'border-sky-200 ring-2 ring-yellow-300',
      label: 'Row 1 (Sky Blue Top)',
    },
    {
      bg: 'bg-gradient-to-b from-[#fdeaf2] via-[#fad4e6] to-[#f7bed9]',
      border: 'border-pink-300',
      text: 'text-slate-950',
      numberText: 'text-slate-950 font-black font-sans',
      blankBg: 'bg-[#fef1f7]/80 border-pink-200/50',
      filigreeColor: 'text-pink-600/30',
      dabbedBg: 'bg-gradient-to-br from-pink-600 via-rose-500 to-fuchsia-700 text-white',
      dabbedText: 'text-white font-black',
      dabbedBorder: 'border-pink-200 ring-2 ring-yellow-300',
      label: 'Row 2 (Rose Pink Mid)',
    },
    {
      bg: 'bg-gradient-to-b from-[#f2faea] via-[#e2f5d2] to-[#d1efb8]',
      border: 'border-lime-300',
      text: 'text-slate-950',
      numberText: 'text-slate-950 font-black font-sans',
      blankBg: 'bg-[#f7fcf2]/80 border-lime-200/50',
      filigreeColor: 'text-emerald-600/30',
      dabbedBg: 'bg-gradient-to-br from-emerald-600 via-teal-500 to-lime-600 text-white',
      dabbedText: 'text-white font-black',
      dabbedBorder: 'border-lime-200 ring-2 ring-yellow-300',
      label: 'Row 3 (Mint Lime Bot)',
    },
  ],
  cellBlankBg: 'bg-purple-950/20 border-purple-950/40',
  cellNormalBg: 'bg-slate-900/90',
  cellNormalText: 'text-amber-100',
  cellNormalBorder: 'border-amber-800/60',
  cellNormalHover: 'hover:border-amber-300 hover:bg-amber-950/50',
  cellDabbedBg: 'bg-gradient-to-br from-amber-400 via-yellow-400 to-amber-600',
  cellDabbedText: 'text-slate-950 font-black',
  cellDabbedBorder: 'border-yellow-200 shadow-lg shadow-amber-500/40',
  cellCurrentBg: 'bg-gradient-to-br from-white to-amber-100 text-slate-950 ring-2 ring-yellow-200',
  checkBadge: 'bg-slate-950 text-amber-300',
  claimPillActive: 'bg-gradient-to-r from-yellow-300 via-amber-400 to-yellow-500 text-slate-950 font-black',
  printBorder: 'border-amber-400',
  printBg: 'from-[#1c1230] via-[#0f091c] to-[#1c1230]',
  printCellText: 'text-amber-200',
  printWatermark: 'text-amber-400',
};

/**
 * Returns the effective visual palette for a ticket.
 * If theme is 'multi' or not specified, returns MULTI_CARNIVAL_THEME or rotates based on ticketIndex.
 */
export function getTicketTheme(themeId?: TicketColorThemeId | string, ticketIndex: number = 0): TicketColorTheme {
  if (themeId && themeId in TICKET_COLOR_PALETTES) {
    return TICKET_COLOR_PALETTES[themeId as Exclude<TicketColorThemeId, 'multi'>];
  }

  if (themeId === 'multi' || !themeId) {
    return MULTI_CARNIVAL_THEME;
  }

  const key = COLOR_KEYS[Math.abs(ticketIndex) % COLOR_KEYS.length];
  return TICKET_COLOR_PALETTES[key] || MULTI_CARNIVAL_THEME;
}

/**
 * Returns a random distinct color key
 */
export function getRandomColorKey(): Exclude<TicketColorThemeId, 'multi'> {
  const idx = Math.floor(Math.random() * COLOR_KEYS.length);
  return COLOR_KEYS[idx];
}
